### ISSUE TITLE
Ghép giao diện đăng nhập vào code

### ISSUE THREAD

**Issue by trong7a2002** [HiamKaito/NUMBER_FINDING_GAME#17]

**Comment by trong7a2002** [comment]
-Đăng kí
-Đăng nhập
-Profile

**Comment by HiamKaito** [comment]
https://images-ext-1.discordapp.net/external/DqZ-NGI6ZgujFUQ7i1VnyhLKlLet44wzTrVAEtOGCSU/%3Fcid%3D73b8f7b15dcb6a30b8a9b294bd8b5391f268232da4b3de23%26rid%3Dgiphy.mp4%26ct%3Dg/https/media2.giphy.com/media/C23ddgFcaYyNA9bnps/giphy.mp4

**Comment by HiamKaito** [comment]
![image](https://user-images.githubusercontent.com/52872325/144463521-77a52f4a-49f1-4ac6-82db-70f15d86f131.png)
