### ISSUE TITLE
-Ghép gameplay

### ISSUE THREAD

**Issue by trong7a2002** [HiamKaito/NUMBER_FINDING_GAME#18]
Edit

**Comment by trong7a2002** [comment]
-Gameplay

**Comment by HiamKaito** [comment]
- [ ] **Server gửi Map và Client Nhận Map**
- [ ] **Client tải map lên màn hình**
- [ ] **Client chọn số và gửi lại server**

**Comment by HiamKaito** [comment]
![image](https://user-images.githubusercontent.com/52872325/144462890-2dc7dafd-c0e6-4822-a709-f72175f6eeec.png)

**Comment by HiamKaito** [comment]
> ![image](https://user-images.githubusercontent.com/52872325/144462890-2dc7dafd-c0e6-4822-a709-f72175f6eeec.png)

Nice
